### ISSUE TITLE
Missing arm64 Binary

### ISSUE THREAD

**Issue by moriel5** [deltalab-org/deltalab-android#13]
Is there a reason why the arm64 binary is missing, or any of the arch-specific binaries other than arm32 (armv7) and 32-bit x86?

**Comment by adbenitez** [comment]
hi, the 32bit alternatives should work for the 64bit arch, ex. if you have armv8 just install the armv7 apk, that is what I am using in my armv8 phone

**Comment by moriel5** [comment]
That is true, and I am not worried about it not working.
I'm just curious as to why this is the situation, as 64bit binaries could potentially make better use of resources.

**Comment by adbenitez** [comment]
the reason was to reduce the apk size of the "universal" variant that is the one uploaded to Apklis store, on IzzyOnDroid only the armv7 is uploaded there so there was no need for armv8 builds etc.

 if I could generate the universal apk without including the armv8 etc. and still generate the independent arch builds I would, so if you know how, contributions welcome

closing the issue as there is no bug or problem just a question replied with this message, thanks for caring! :heart:

**Comment by moriel5** [comment]
That certainly makes sense.

I wonder if SAI could be of help here, if only to have 64bit binaries on GitHub, or if it would be more of a hindrance.

**Comment by lyynd** [comment]
I am using Pixel 8 Pro (husky) and I can neither use armv7 nor universal builds, because this phone only supports arm64. So having these builds is actually pretty important. Please reopen. @adbenitez

**Comment by adbenitez** [comment]
Hi @lyynd thanks for letting me know, I will enable back armv8

**Comment by adbenitez** [comment]
arm64 is now available in the new release 1.43.3
