### ISSUE TITLE
DeltaLab Tries Opening Any and All Links.

### ISSUE THREAD

**Issue by moriel5** [deltalab-org/deltalab-android#14]
Currently, I forget since which update, DeltaLab tries opening any link possible to share it.

Usually this is fine, as there are other apps that cam be selected instead from the system flyout, however sometimes it is not, which causes issues, like with ReLabs (3rd party XDA Developers client), where it is impossible to launch the OAuth prompt on account of DeltaLab opening it and trying to share it.

Can anything be done about this?

**Comment by adbenitez** [comment]
that is because at some point when you clicked a link and got a list of apps to choose from, you clicked the "remember my choice" or something like that, to always use deltalab to open links

now you have to go to your phone system settings, looks for "Apps" section, select deltalab and there should be something like "Clear defaults" option, to stopping using the app as default app for some actions

then you should get again an app selector the next time you click a link,

thanks for using DeltaLab! best regards,
adb

**Comment by moriel5** [comment]
Thanks, however this had not happened, as I remember it only starting to happen immediately after one of the newest updates, and I had never set it to be the default for anything.

The settings app corroborates this.

**Comment by adbenitez** [comment]
DeltaLab can't take over your system and decide to open links on its own, so if when you click a link it opens directly with deltalab there are only two options:

a) you set the app as default app to open links
b) you don't have any other apps to handle the link you clicked so the only app that can handle your request, deltalab, is opened

all depends on your actions and your system, there is nothing I can do to solve your problem, it is not a problem in DeltaLab

the only thing I can tell you is to try to install a web browser like this:

Fennec F-Droid (Browse the web)
https://f-droid.org/packages/org.mozilla.fennec_fdroid/

then likely you get prompted with the lists of apps to select when you click a link, otherwise you will need to investigate more carefully what is going on in your phone given the two possibilities I mentioned above

**Comment by moriel5** [comment]
You are certainly correct, and I would have assumed that I indeed do not have another compatible app (despite having three browsers installed, one of which is a Firefox fork), however I am aware that sometimes Android's handling of looks is wonky, and it will act as though one app is the default for no reason (there are multiple reports of this over the years).

Of course, this does not make this a DeltaLab bug, however I would think that it is worth bringing up, just in case this may help code improvement in the future.

By the way, I checked, and Delta Chat does not currently present this behaviour on my device (Razer Phone 2, Stock Android 9, deGoogled).

**Comment by adbenitez** [comment]
it doesn't happen with Delta Chat because Delta Chat doesn't handle link clicks, you can't "open" links with delta chat, it is a feature of deltalab, why? because people that use bots in DeltaLab to browse the web via bots can then click on links and get redirected to DeltaLab and can keep requesting links to the bots

if you can't figure out how to change DeltaLab as default browser in your system, then maybe you should switch to Delta Chat and uninstall DeltaLab, the browser I shared with you is a Firefox fork it should have an option of "set as default browser" or so, or the tip of installing a new browser should solve your issue otherwise, there is no "code improvement" possible, that would be removing the mentioned feature

**Comment by moriel5** [comment]
Whoa, what happened?

I only installed and tested Delta Chat in order to make my report more complete, and I had fully agreed with the premise you brought up, but pointed out that Android itself does also have bugs, as evidenced by logs brought by users over the years.

In any case, your recommendation is what helped me understand the situation better, since it actually worked, and I reported back to you the results by updating my posts before your last reply, and I certainly thank you for helping me resolve and understand what happened on my end.

**Comment by adbenitez** [comment]
> Whoa, what happened?
> 
> I only installed and tested Delta Chat in order to make my report more complete, and I had fully agreed with the premise you brought up, but pointed out that Android itself does also have bugs, as evidenced by logs brought by users over the years.

sorry the late reply, realized now what you meant with this, sorry, my previous message didn't mean to be rude or angry, I am also the maintainer of the official Delta Chat for android, so recommending you to uninstall DeltaLab and switch to Delta Chat was just offering an alternative to solve your issue at hand :sweat_smile: 

since it seems you solved the situation, I am closing this issue, thanks a lot for your report and once again sorry for any misunderstanding :sweat_smile:

**Comment by moriel5** [comment]
No worries, I thought that you had merely had a bad day, and as a result weren't able to fully take in what I had wrote at the time (it happens to everyone, after all), so I was not offended, only surprised.

Regardless, I am glad that the misunderstandings are behind us, and can only wish for the best for you, and for the continued development of Delta Chat.
